languageCode = "it"
languageName = "Italiano"
weight = 2
title = "Zanzibar"

[params]
  displayName = "Italiano"
  isoCode = "it"
  rtl = false
  dateFormat = "9 July 2004"
  logo = "img/zanzilogo_testo.png"
  description = "Un potente, leggero bar per Olivarella."

[params.author]
  name = "Zanzibar"
  image = "img/zanzilogo.png"
  headline = "Questo Ã¨ l'ipotetico subheadline"
  bio = "Questo va cambiata in Bio (ancora non so dove)"
  links = [
    { instagram = "https://github.com/nunocoracao/blowfish" },
    { facebook = "https://github.com/nunocoracao/blowfish" },

  ]